//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrabblos.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scrabblos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] board {
            get {
                object obj = ResourceManager.GetObject("board", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný A	11835863
        ///Á	4310
        ///À	211
        ///Ą	105
        ///AA	545
        ///AAA	564
        ///AALTONEN	218
        ///AARON	991
        ///AARONA	164
        ///AARONE	188
        ///AB	1613
        ///ABALKIN	118
        ///ABB	791
        ///ABBA	264
        ///ABBÁS	161
        ///ABBEY	248
        ///ABBOTT	172
        ///ABBY	133
        ///ABC	2015
        ///ABDIKACI	234
        ///ABDUL	126
        ///ABE	334
        ///ABECEDU	226
        ///ABECEDY	1002
        ///ABEL	132
        ///ÁBEL	417
        ///ABELARD	108
        ///ÁBER	133
        ///ABF	443
        ///ABCHÁZIE	133
        ///ABCHÁZII	145
        ///ABIE	110
        ///ABIGAIL	389
        ///ABL	275
        ///ABN	289
        ///ABNORMÁLNĚ	107
        ///ABNORMÁLNÍ	414
        ///ABONENTNÍ	104
        ///ABRAHAM	1463
        ///ABRAHÁM	333
        ///ABRAHAMA	415
        ///ABRAM	515
        ///ABRAMOVIČ	118
        ///ABS	798
        ///ABSENCE	4140 [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string dict {
            get {
                return ResourceManager.GetString("dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] mirek {
            get {
                object obj = ResourceManager.GetObject("mirek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tile_ {
            get {
                object obj = ResourceManager.GetObject("tile_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileA {
            get {
                object obj = ResourceManager.GetObject("tileA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileÁ {
            get {
                object obj = ResourceManager.GetObject("tileÁ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileB {
            get {
                object obj = ResourceManager.GetObject("tileB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileC {
            get {
                object obj = ResourceManager.GetObject("tileC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileČ {
            get {
                object obj = ResourceManager.GetObject("tileČ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileD {
            get {
                object obj = ResourceManager.GetObject("tileD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileĎ {
            get {
                object obj = ResourceManager.GetObject("tileĎ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileE {
            get {
                object obj = ResourceManager.GetObject("tileE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileÉ {
            get {
                object obj = ResourceManager.GetObject("tileÉ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileĚ {
            get {
                object obj = ResourceManager.GetObject("tileĚ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileF {
            get {
                object obj = ResourceManager.GetObject("tileF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileG {
            get {
                object obj = ResourceManager.GetObject("tileG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileH {
            get {
                object obj = ResourceManager.GetObject("tileH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileI {
            get {
                object obj = ResourceManager.GetObject("tileI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileÍ {
            get {
                object obj = ResourceManager.GetObject("tileÍ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileJ {
            get {
                object obj = ResourceManager.GetObject("tileJ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileK {
            get {
                object obj = ResourceManager.GetObject("tileK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileL {
            get {
                object obj = ResourceManager.GetObject("tileL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileM {
            get {
                object obj = ResourceManager.GetObject("tileM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileN {
            get {
                object obj = ResourceManager.GetObject("tileN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileŇ {
            get {
                object obj = ResourceManager.GetObject("tileŇ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileO {
            get {
                object obj = ResourceManager.GetObject("tileO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileÓ {
            get {
                object obj = ResourceManager.GetObject("tileÓ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileP {
            get {
                object obj = ResourceManager.GetObject("tileP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileR {
            get {
                object obj = ResourceManager.GetObject("tileR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileŘ {
            get {
                object obj = ResourceManager.GetObject("tileŘ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileS {
            get {
                object obj = ResourceManager.GetObject("tileS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileŠ {
            get {
                object obj = ResourceManager.GetObject("tileŠ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileT {
            get {
                object obj = ResourceManager.GetObject("tileT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileŤ {
            get {
                object obj = ResourceManager.GetObject("tileŤ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileU {
            get {
                object obj = ResourceManager.GetObject("tileU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileÚ {
            get {
                object obj = ResourceManager.GetObject("tileÚ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileŮ {
            get {
                object obj = ResourceManager.GetObject("tileŮ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileV {
            get {
                object obj = ResourceManager.GetObject("tileV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileX {
            get {
                object obj = ResourceManager.GetObject("tileX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileY {
            get {
                object obj = ResourceManager.GetObject("tileY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileÝ {
            get {
                object obj = ResourceManager.GetObject("tileÝ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileZ {
            get {
                object obj = ResourceManager.GetObject("tileZ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileŽ {
            get {
                object obj = ResourceManager.GetObject("tileŽ", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
