//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrabblos.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scrabblos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný A	11835863
        ///Á	4310
        ///À	211
        ///Ą	105
        ///AA	545
        ///AAA	564
        ///AALTONEN	218
        ///AARON	991
        ///AARONA	164
        ///AARONE	188
        ///AB	1613
        ///ABALKIN	118
        ///ABB	791
        ///ABBA	264
        ///ABBÁS	161
        ///ABBEY	248
        ///ABBOTT	172
        ///ABBY	133
        ///ABC	2015
        ///ABDIKACI	234
        ///ABDUL	126
        ///ABE	334
        ///ABECEDU	226
        ///ABECEDY	1002
        ///ABEL	132
        ///ÁBEL	417
        ///ABELARD	108
        ///ÁBER	133
        ///ABF	443
        ///ABCHÁZIE	133
        ///ABCHÁZII	145
        ///ABIE	110
        ///ABIGAIL	389
        ///ABL	275
        ///ABN	289
        ///ABNORMÁLNĚ	107
        ///ABNORMÁLNÍ	414
        ///ABONENTNÍ	104
        ///ABRAHAM	1463
        ///ABRAHÁM	333
        ///ABRAHAMA	415
        ///ABRAM	515
        ///ABRAMOVIČ	118
        ///ABS	798
        ///ABSENCE	4140 [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string dict {
            get {
                return ResourceManager.GetString("dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] mirek {
            get {
                object obj = ResourceManager.GetObject("mirek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        internal static byte[] tileS {
            get {
                object obj = ResourceManager.GetObject("tileS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
